export const alphabetSoundPairs = [
    { letter: 'A', image: '/letters/Aa.png', sound: '/sounds/a.mp3' },
    { letter: 'B', image: '/letters/Bb.png', sound: '/sounds/b.mp3' },
    { letter: 'C', image: '/letters/Cc.png', sound: '/sounds/c.mp3' },
    { letter: 'D', image: '/letters/Dd.png', sound: '/sounds/d.mp3' },
    { letter: 'E', image: '/letters/Ee.png', sound: '/sounds/e.mp3' },
    { letter: 'F', image: '/letters/Ff.png', sound: '/sounds/f.mp3' },
    { letter: 'G', image: '/letters/Gg.png', sound: '/sounds/g.mp3' },
    { letter: 'H', image: '/letters/Hh.png', sound: '/sounds/h.mp3' },
    { letter: 'I', image: '/letters/Ii.png', sound: '/sounds/i.mp3' },
    { letter: 'J', image: '/letters/Jj.png', sound: '/sounds/j.mp3' },
    { letter: 'K', image: '/letters/Kk.png', sound: '/sounds/k.mp3' },
    { letter: 'L', image: '/letters/Ll.png', sound: '/sounds/l.mp3' },
    { letter: 'M', image: '/letters/Mm.png', sound: '/sounds/m.mp3' },
    { letter: 'N', image: '/letters/Nn.png', sound: '/sounds/n.mp3' },
    { letter: 'O', image: '/letters/Oo.png', sound: '/sounds/o.mp3' },
    { letter: 'P', image: '/letters/Pp.png', sound: '/sounds/p.mp3' },
    { letter: 'Q', image: '/letters/Qq.png', sound: '/sounds/q.mp3' },
    { letter: 'R', image: '/letters/Rr.png', sound: '/sounds/r.mp3' },
    { letter: 'S', image: '/letters/Ss.png', sound: '/sounds/s.mp3' },
    { letter: 'T', image: '/letters/Tt.png', sound: '/sounds/t.mp3' },
    { letter: 'U', image: '/letters/Uu.png', sound: '/sounds/u.mp3' },
    { letter: 'V', image: '/letters/Vv.png', sound: '/sounds/v.mp3' },
    { letter: 'W', image: '/letters/Ww.png', sound: '/sounds/w.mp3' },
    { letter: 'X', image: '/letters/Xx.png', sound: '/sounds/x.mp3' },
    { letter: 'Y', image: '/letters/Yy.png', sound: '/sounds/y.mp3' },
    { letter: 'Z', image: '/letters/Zz.png', sound: '/sounds/z.mp3' },
]